### ISSUE TITLE
cv::resize ocl error when using cuda

### ISSUE THREAD

**Issue by xuchao1688** [facebookresearch/video-nonlocal-net#11]
Because of conflict between opencl and cuda, you should add `cv::ocl::setUseOpenCL(false);` and include the head file `#include <opencv2/core/ocl.hpp>`.
By the way, I have realized data blob fetched from preprocessed video RGB images, which will dramaticly shorten the whole training cost from 30 days which process raw video data while runtime to 4 days. We can talk about this code to ensure its correctness if you'd like to.

**Comment by xiaolonw** [comment]
Hi, I have not encountered the problem of resize and the data processing is actually all via cpu before feeding into the CNN, so it should not conflict with cuda?  

The point of reading from raw videos is actually to make training faster. We find reading images takes much larger hard disk and much slower, which makes it hard to scale up.

For me performing video decoding on the fly only takes 2-3 days for one experiment cycle. You can try to increase the reading threads to speed up the IO, or maybe better CPUs are required.

**Comment by xuchao1688** [comment]
What's your CPU info? My CPU is double  E5-2850V4.

**Comment by xiaolonw** [comment]
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               2101.000
BogoMIPS:              4199.40
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

**Comment by liu666666** [comment]
Thanks for the nice job! @xiaolonw 

I find that the non-local encodes videos very slowly on my server, my cpu is 
Moreover, the log shows that 

| Train ETA: 3 days, 10:37:28 LR: 0.00500000  Iters [300/40000] [0.02ep]  Time 2.827  Loss  0.2272  top1   6.250 top5   6.250
| Train ETA: 3 days, 11:06:32 LR: 0.00500000  Iters [310/40000] [0.02ep]  Time 8.433  Loss  0.2145  top1   6.250 top5   6.250
| Train ETA: 3 days, 11:04:33 LR: 0.00500000  Iters [320/40000] [0.02ep]  Time 6.428  Loss  0.6102  top1  31.250 top5  31.250
| Train ETA: 3 days, 11:04:39 LR: 0.00500000  Iters [330/40000] [0.02ep[avi @ 0x7d7c844b5260] non-interleaved AVI
[avi @ 0x7d7c9052ac80] non-interleaved AVI
[swscaler @ 0x7d7c78593560] deprecated pixel format used, make sure you did set range correctly.

why show the "non-interleaved AVI"?

Could you please tell me how to increase the reading threads to speed up the IO?
