### ISSUE TITLE
error when training:  status == ncclSuccess. 2 vs 0

### ISSUE THREAD

**Issue by gooners1886** [facebookresearch/video-nonlocal-net#14]
centos system 

I prepared the  lmdb file for  training and val set. then i run 

sh run_i3d_baseline_300k_4gpu.sh
I get this error: 

[E net_dag.cc:188] Exception from operator chain starting at '' (type 'NCCLAllreduce'): caffe2::EnforceNotMet: [enforce fail at cuda_nccl_gpu.cc:24] status == ncclSuccess. 2 vs 0.  Error at: /root/code/official_caffe2/caffe2/caffe2/contrib/nccl/cuda_nccl_gpu.cc24: system error Error from operator: 
input: "gpu_0/pred_b_grad" input: "gpu_1/pred_b_grad" input: "gpu_2/pred_b_grad" input: "gpu_3/pred_b_grad" output: "gpu_0/pred_b_grad" output: "gpu_1/pred_b_grad" output: "gpu_2/pred_b_grad" output: "gpu_3/pred_b_grad" name: "" type: "NCCLAllreduce" device_option { device_type: 1 cuda_gpu_id: 0 }

What should I do?

**Comment by xiaolonw** [comment]
You will need to install nccl, i have installed nccl from the official NVIDIA website. But you might try:
conda install -c anaconda nccl
and then redo cmake, you should see in the cmake log that NCCL is "ON"

if it does not work, you can also follow issue:
https://github.com/facebookresearch/video-nonlocal-net/issues/5
which turns NCCL off in the code.
