### ISSUE TITLE
Your code use whole raw video instead of video segmentations according to annotation file when training?

### ISSUE THREAD

**Issue by xuchao1688** [facebookresearch/video-nonlocal-net#15]
Traditionally, the training video input should be segmentations cropped from raw videos according to the annotation file which tells the segmentation when to start and when to end. Then the training input will sample the clip from these segmentations. However, I cannot find your code doing such thing. Do your code just sample the clip from the whole raw video data without any cropping work?

**Comment by xuchao1688** [comment]
The clip which i mean is the video segmentation given by annotation file.

**Comment by xiaolonw** [comment]
the current video op does not support annotation with specifying start and end frames. What the op does is firstly decode the whole video, and then randomly crop (in training time) the specific number of frames (e.g. 32 frames) as the input to the model. 

The number of frames and the sampling rate can be specified in the config file, for example: 
https://github.com/facebookresearch/video-nonlocal-net/blob/master/configs/DBG_kinetics_resnet_8gpu_c2d_nonlocal_affine_400k.yaml#L38

  VIDEO_LENGTH: 32
  SAMPLE_RATE: 4

means we sample 32 frames from the video, and each frame is sampling from every 4 frames. So the actual duration of the input video is across 32 x 4 frames. 

Although we do not offer the code for specifying the start and end frame for training here, I have actually done it without much efforts myself, and it works very well with fine-tuning on datasets like Charades.

**Comment by xiaolonw** [comment]
Can you send me a email to: xiaolonw@cs.cmu.edu ?
