### ISSUE TITLE
Have you know this error under cmake?

### ISSUE THREAD

**Issue by poppingcode** [facebookresearch/video-nonlocal-net#17]
[ 85%] Linking CXX shared module python/caffe2_pybind11_state_gpu.so
[ 85%] Built target caffe2_pybind11_state_gpu
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2#

this is my cmake-output:
[cmake_output.txt](https://github.com/facebookresearch/video-nonlocal-net/files/1967682/cmake_output.txt)

The dir ：/build/Makefile--140 line is : 

![1](https://user-images.githubusercontent.com/33169964/39530268-3299e3b2-4e5b-11e8-90f4-e93e8bc24be1.png)

**Comment by xiaolonw** [comment]
it looks like a protobuf bug. 

you need to make sure the protobuf you used to compile and link is the same one. It is highly possible that you have a protobuf in your libs under /usr and you install another protobuf in anaconda, and in your LD_LIBRARY_PATH you have both. This will confuse the linking process ... you should try to remove one of them, or at least remove one of them out of LD_LIBRARY_PATH
