### ISSUE TITLE
run_test_multicrop.sh ERROR

### ISSUE THREAD

**Issue by kellycvcv** [facebookresearch/video-nonlocal-net#18]
Hi,
Xiaolong,Sorry to intrupt you again!
I meet a new problem when I use run_test_multicrop.sh

for test_iter in range(total_test_net_iters):
       # timer.tic()
        workspace.RunNet(test_model.net.Proto().name)
       # timer.toc()

*** Aborted at 1525368135 (unix time) try "date -d @1525368135" if you are using GNU date ***
PC: @     0x7f91145255ef caffe2::CustomizedVideoInputOp<>::GetClipAndLabelFromDBValue()
*** SIGSEGV (@0x40) received by PID 28 (TID 0x7f9087fff700) from PID 64; stack trace: ***
    @     0x7f916f8654b0 (unknown)
    @     0x7f91145255ef caffe2::CustomizedVideoInputOp<>::GetClipAndLabelFromDBValue()
    @     0x7f9114525d20 caffe2::CustomizedVideoInputOp<>::DecodeAndTransform()
    @     0x7f9114522ef3 std::_Function_handler<>::_M_invoke()
    @     0x7f91144fbb2b caffe2::TaskThreadPool::main_loop()
    @     0x7f90db4e4c80 (unknown)
    @     0x7f916fc016ba start_thread
    @     0x7f916f93741d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)

Wait for your watch!

**Comment by xiaolonw** [comment]
please refer to https://github.com/facebookresearch/video-nonlocal-net/issues/16 for this :)
