### ISSUE TITLE
Is epoch proceeding calculated by a set value in the logs?

### ISSUE THREAD

**Issue by clover978** [facebookresearch/video-nonlocal-net#19]
When finetuning, the proceeding seems to be calculated by kinetic dataset size. I just can't find training size in config.py.

**Comment by xiaolonw** [comment]
if you mean setting the training dataset size for calculating the epoch numbers, it is set in here:
https://github.com/facebookresearch/video-nonlocal-net/blob/master/lib/core/config.py#L78

however, this number does not affect anything in training, it is just for logging.
