### ISSUE TITLE
after “cmake -DCMAKE_INSTALL_PREFIX:PATH=/path/to/caffe2/build/install ..”

### ISSUE THREAD

**Issue by poppingcode** [facebookresearch/video-nonlocal-net#2]
there also have no file-install to implement make -j16 install.

so i check "/home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeError.log"
i want know how to solve it . thanks
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d9137/fast"
/usr/bin/make -f CMakeFiles/cmTC_d9137.dir/build.make CMakeFiles/cmTC_d9137.dir/build
make[1]: Entering directory '/home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d9137.dir/CheckSymbolExists.c.o
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cc    -o CMakeFiles/cmTC_d9137.dir/CheckSymbolExists.c.o   -c /home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_d9137
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d9137.dir/link.txt --verbose=1
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cc      -rdynamic CMakeFiles/cmTC_d9137.dir/CheckSymbolExists.c.o  -o cmTC_d9137 
CMakeFiles/cmTC_d9137.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_d9137.dir/build.make:97: recipe for target 'cmTC_d9137' failed
make[1]: *** [cmTC_d9137] Error 1
make[1]: Leaving directory '/home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_d9137/fast' failed
make: *** [cmTC_d9137/fast] Error 2

File /home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2ff92/fast"
/usr/bin/make -f CMakeFiles/cmTC_2ff92.dir/build.make CMakeFiles/cmTC_2ff92.dir/build
make[1]: Entering directory '/home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2ff92.dir/CheckFunctionExists.c.o
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_2ff92.dir/CheckFunctionExists.c.o   -c /home/kong.ye/install_pakage/yes/envs/caffe2/share/cmake-3.9/Modules/CheckFunctionExists.c
Linking C executable cmTC_2ff92
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2ff92.dir/link.txt --verbose=1
/home/kong.ye/install_pakage/yes/envs/caffe2/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_2ff92.dir/CheckFunctionExists.c.o  -o cmTC_2ff92 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2ff92.dir/build.make:97: recipe for target 'cmTC_2ff92' failed
make[1]: *** [cmTC_2ff92] Error 1
make[1]: Leaving directory '/home/kong.ye/action_recognize/caffe2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2ff92/fast' failed
make: *** [cmTC_2ff92/fast] Error 2

**Comment by xiaolonw** [comment]
so is it an error during cmake? 

Can you show me the screenshot of the error during cmake instead of this log?

**Comment by poppingcode** [comment]
[nohup.log](https://github.com/facebookresearch/video-nonlocal-net/files/1901818/nohup.log)

**Comment by poppingcode** [comment]
i download  https://github.com/xiaolonw/caffe2
after “cmake -DCMAKE_INSTALL_PREFIX:PATH=/path/to/caffe2/build/install ..”
i write the output to the follwing file：the file will show more details,
1.:
[xiaolonw-.log](https://github.com/facebookresearch/video-nonlocal-net/files/1902966/xiaolonw-.log)
For easy reading, you can use notepad++ to open，

one of error is:
CMake Error at CMakeLists.txt:188 (add_subdirectory):
  The source directory
    /home/kong.ye/action_recognize/non-local-net/xiaolonw-caffe2/caffe2/modules
  does not contain a CMakeLists.txt file.
Please check if it is missing,Because I didn't find it in your GitHub

one of error is something about peachpy-download.the file will show more details,

**Comment by xiaolonw** [comment]
it looks like it is complaining "  Generated cmake files are only fully available if one builds with system glog, gflags and protobuf."

Have you install glog, gflags and protobuf? 

conda install --yes glog && \
conda install --yes gflags && \
conda install --yes protobuf

**Comment by poppingcode** [comment]
i have install them.
（1）one of error is:
CMake Error at CMakeLists.txt:188 (add_subdirectory):
The source directory
/home/kong.ye/action_recognize/non-local-net/xiaolonw-caffe2/caffe2/modules
does not contain a CMakeLists.txt file.
Please check if it is missing,Because I didn't find it in your GitHub

**Comment by xiaolonw** [comment]
it is actually right here: 
https://github.com/xiaolonw/caffe2/blob/master/CMakeLists.txt

when you do clone, did you clone recursively? like:
git clone --recursive https://github.com/xiaolonw/caffe2

**Comment by poppingcode** [comment]
i just download it from github web,because when i do " git clone --recursive https://github.com/xiaolonw/caffe2",it download slowly so that i Frequently disconnect.

so i wil downlaod CMakeLists.txt from https://github.com/xiaolonw/caffe2/blob/master/CMakeLists.txt,and copy it to xiaolonw-caffe2/caffe2/modules.
thanks

**Comment by xiaolonw** [comment]
I think you have to clone recursively, there are a lot of dependencies to download together with caffe2 via using --recursive

**Comment by poppingcode** [comment]
Can you send me mail directly for "xiaolonw/caffe2",
When I download it, I always disconnect。
my email ：tiankong2586@gmail.com

**Comment by xiaolonw** [comment]
can you try to clone the official version of caffe2? 
https://github.com/caffe2/caffe2

then follow:
https://github.com/facebookresearch/video-nonlocal-net/blob/master/INSTALL.md#getting-official-caffe2

**Comment by xiaolonw** [comment]
hi, you cannot just use "/path/to/caffe2/build/install/share/cmake/Caffe2" 
you should replace "/path/to/" to the place where caffe2 is downloaded during cmake

**Comment by poppingcode** [comment]
ok，thank you vert much .i do cmake in the build,so i replace it to
/home/username/caffe2-office/caffe2/build

**Comment by xieyufei1993** [comment]
@poppingcode @RyanCV @xiaolonw Hi, do you have third_party error when u using git clone --recursive to download the caffe2? I have this error and want to know how to solve it. Thanks
