### ISSUE TITLE
Can't find affine_model_400k.pkl

### ISSUE THREAD

**Issue by w452261940** [facebookresearch/video-nonlocal-net#21]
Hi,
I met some problem When I want to train the model i3d_nlnet_affine_400k, I noted that you said a converted pretrained model was provided in pretrained_model.tar.gz. But I did't find it. The only model I can use is affine_model_30k.pkl in run_i3d_baseline. 

Can I use this  converted model to train i3d_nlnet_affine_400k ?
Or if  it works that download your i3d_baseline model and convert it into affine_400k.pkl ?

Thanks!

**Comment by xiaolonw** [comment]
Hi, 
you can use affine_model_30k.pkl as a pre-trained model for i3d_nlnet_affine_400k, you actually do not need to pre-trained the non-local layers with the "short clip" network. 
We also find that pre-training with 300k iterations or 400k iterations does not make a difference, so you can just directly use affine_model_30k.pkl .

btw affine_model_30k is trained with 300k so it is a typo.
