### ISSUE TITLE
cfg.TRAIN.COMPUTE_PRECISE_BN

### ISSUE THREAD

**Issue by jetyingjia** [facebookresearch/video-nonlocal-net#22]
I find when save the checkpoint, the code will "compute_and_update_bn_stats", it will compute BN in a sufficiently large training batch.  Through this operation it will get a "PRECISE_BN", which is good than 8 traing samples(per GPU 8 samples with 8 GPUs). This operation will get a good performnce?
   I find in my own caffe code, the performance (16 samples per GPU) is better than (8 samples per GPU), about 1.5%.

**Comment by xiaolonw** [comment]
Hi, 
PRECISE_BN deos not affect the performance in the final model really, it just makes the train/val error curve looks better when you visualize it. 

I have also tried using 16 samples per batch, but i actually did not get much improvement in the case of training with 400K iterations.

**Comment by jetyingjia** [comment]
Thank you for your replay, when I use 16 samples per batch, I can get the performacne in the paper, but  8 samples per batch is 1.5% than 16 samples per batch.

**Comment by xiaolonw** [comment]
Hi, 
In that case, i am actually suspecting your lr schedule might not be well adjusted. If you are using a 4GPUs machine and running with our 8GPU script, remember to adjust the lr by using lr = lr/2 and double the training iterations, with batchsize=8 samples per GPU.

**Comment by jetyingjia** [comment]
Hi,
ALL training use the same configs(base_lr=0.01 and total training epochs=90), except the batch_size per GPU(8 or 16). 

Because I use my own code and pre_train model(not your release code and pre_train model), the config may be not suitable for me?  I have try some experiments, expect have a good result.
