### ISSUE TITLE
deprecated pixel format used, make sure you did set range correctly  [during training]

### ISSUE THREAD

**Issue by gooners1886** [facebookresearch/video-nonlocal-net#27]
I use kinetics dataset to train the non-local model. I get some output during training:

[swscaler @ 0x7d8770033900] deprecated pixel format used, make sure you did set range correctly
| Train ETA: 2 days, 19:18:01 LR: 0.00500000  Iters [150/300000] [0.00ep]  Time 0.761  Loss  5.3394  top1  96.875 top5  90.625
| Train ETA: 2 days, 18:39:42 LR: 0.00500000  Iters [160/300000] [0.00ep]  Time 0.715  Loss  4.9686  top1  81.250 top5  71.875
| Train ETA: 2 days, 18:38:18 LR: 0.00500000  Iters [170/300000] [0.00ep]  Time 0.674  Loss  5.0748  top1  96.875 top5  81.250
| Train ETA: 2 days, 18:20:39 LR: 0.00500000  Iters [180/300000] [0.00ep]  Time 0.583  Loss  4.8989  top1  93.750 top5  87.500
| Train ETA: 2 days, 18:09:08 LR: 0.00500000  Iters [190/300000] [0.00ep]  Time 0.633  Loss  5.4064  top1 100.000 top5  93.750
| Train ETA: 2 days, 17:54:54 LR: 0.00500000  Iters [200/300000] [0.00ep]  Time 0.639  Loss  5.1758  top1  90.625 top5  81.250
| Train ETA: 2 days, 17:35:07 LR: 0.00500000  Iters [210/300000] [0.01ep]  Time 0.684  Loss  5.2266  top1  93.750 top5  90.625
| Train ETA: 2 days, 17:14:03 LR: 0.00500000  Iters [220/300000] [0.01ep]  Time 0.794  Loss  5.3617  top1  96.875 top5  87.500
| Train ETA: 2 days, 16:52:24 LR: 0.00500000  Iters [230/300000] [0.01ep]  Time 0.945  Loss  5.0694  top1  93.750 top5  78.125
[swscaler @ 0x7d875802c5a0] deprecated pixel format used, make sure you did set range correctly

what does this "deprecated pixel format used, make sure you did set range correctly"  means? 
Does it mean there exist something wrong of my training video?
Will this cause a bad accurary??

**Comment by xiaolonw** [comment]
It is a warning in ffmpeg decoding. It has not happened to me. I am guessing it is the difference of ffmpeg version. It should not affect accuracy.

**Comment by gooners1886** [comment]
Thank you for your answer.
My ffmpeg version is the same as the version recommended in the INSTALL.md. 
(caffe2) [root@67221fae-1aec-4975-bfd1-60382aeb8968 ~]#conda list ffmpeg
# packages in environment at /root/anaconda2/envs/caffe2:
#
# Name                    Version                   Build  Channel
ffmpeg                    3.2.4                         3    conda-forge


Should I use a newer one?

**Comment by xiaolonw** [comment]
then i think it should be fine
