### ISSUE TITLE
Do you use the positional encoding?

### ISSUE THREAD

**Issue by PkuRainBow** [facebookresearch/video-nonlocal-net#31]
It seems that both the original self-attention and the related work(Relation Networks for Object Detection) all use the "positional encoding" help learn better affinity matrix.

I am wondering have you tried using the positional features, if so, it would be great if you could share the performance with the positional features.

**Comment by xiaolonw** [comment]
no, I did not. I have actually tried it for kinetics, but did not find it help much.

**Comment by PkuRainBow** [comment]
Thanks, I also failed to use it correctly .......
