### ISSUE TITLE
can't find -lnnpack 

### ISSUE THREAD

**Issue by hengshanji** [facebookresearch/video-nonlocal-net#45]
I have install NNPACK using ninja, but when make caffe2, I got an error 
usr/bin/ld: 找不到 -lnnpack
/usr/bin/ld: 找不到 -lpthreadpool
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:6645: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:1138: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by callmemaxi** [comment]
Hi, Did you find any fix for this?
