### ISSUE TITLE
broadcast_computed_params=False

### ISSUE THREAD

**Issue by jetyingjia** [facebookresearch/video-nonlocal-net#5]
Sorry to trouble you again. I have two questions.
a.  In default, the broadcast_computed_params=True, I find in this porject(/lib/models/model_builder_video.py), broadcast_computed_params=False, the reason is ?

b. about the NCCL(terminate called after throwing an instance of 'caffe2::EnforceNotMet' what(): [enforce fail at cuda_nccl_gpu.cc:40] status == ncclSuccess. 2 vs 0. Error at: ), if I set the cfg.DEBUG=True, that means 
data_parallel_model.Parallelize_GPU(
            model,
            input_builder_fun=input_builder_fun,
            forward_pass_builder_fun=forward_pass_builder_fun,
            param_update_builder_fun=param_update_builder_fun,
            devices=gpus,
            rendezvous=rendezvous_ctx,
            broadcast_computed_params=False,
            optimize_gradient_memory=cfg.MODEL.MEMONGER,
            use_nccl=not cfg.DEBUG,  # org: True
        )
use_nccl=False, this problem can be solved. 
I worry is there effects on the performances.

Thank you in advance!

**Comment by xiaolonw** [comment]
"broadcast_computed_params" is actually for training across multiple machines, our current code does not support that, so it is false. 

NCCL is used to accelerate the multi-GPU communication speed. I suggest you to just install NCCL. I have not tried the code without NCCL, but i think it should be just a matter of training speed.

**Comment by KaimingHe** [comment]
Part of this code was inherited from a very early version of code (basically, early Detectron), when Caffe2 did not have a mature data parallel modeling. So some parallel efforts, such as broadcasting, are done explicitly, and the new options added to data_parallel_model may do the same thing and thus disabled.

**Comment by jetyingjia** [comment]
@xiaolonw@KaimingHe,
Thank you for answering these questions. 
Now, I diabled the NCCL, the training seems OK.(I install the NCCL, but it doesn‘t work...)

**Comment by jetyingjia** [comment]
@xiaolonw
@KaimingHe,
Thank you for answering these questions.
Now, I diabled the NCCL, the training seems OK.(I install the NCCL, but it doesn‘t work...)
