### ISSUE TITLE
video/customized_video_io.h 

### ISSUE THREAD

**Issue by l2009312042** [facebookresearch/video-nonlocal-net#54]
in  video/customized_video_io.h   
caffe2  use caffe's header   #include "caffe/proto/caffe.pb.h"

so   i set the dir   in CMakefilelist 
include_directories(/home/opt/caffe/.build_release/include)

mkdir build
cmake ..
make -j4
report the following errors :

/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20033:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::TileParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20033:56: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::TileParameter>(GetArenaNoVirtual());
                                                        ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::WindowDataParameter* caffe::LayerParameter::mutable_window_data_param()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20091:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::WindowDataParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20091:62: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::WindowDataParameter>(GetArenaNoVirtual());
                                                              ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::TransformationParameter::release_mean_file()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20246:21: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return mean_file_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                     ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::BiasParameter::mutable_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20830:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:20830:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::ConvolutionParameter::mutable_weight_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21280:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21280:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::ConvolutionParameter::mutable_bias_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21338:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21338:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::DataParameter::release_source()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21552:18: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return source_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                  ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::DataParameter::release_mean_file()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:21715:21: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return mean_file_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                     ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::EmbedParameter::mutable_weight_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22255:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22255:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::EmbedParameter::mutable_bias_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22313:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22313:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::HDF5DataParameter::release_source()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22524:18: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return source_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                  ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::HDF5OutputParameter::release_file_name()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22642:21: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return file_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                     ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::ImageDataParameter::release_source()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22741:18: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return source_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                  ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::ImageDataParameter::release_mean_file()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:22975:21: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return mean_file_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                     ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::ImageDataParameter::release_root_folder()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23089:23: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return root_folder_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                       ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'std::__cxx11::string* caffe::InfogainLossParameter::release_source()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23159:18: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'ReleaseNonDefaultNoArena'
   return source_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                  ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::InnerProductParameter::mutable_weight_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23280:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23280:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::FillerParameter* caffe::InnerProductParameter::mutable_bias_filler()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23338:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
               ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23338:58: error: expected primary-expression before '>' token
     auto* p = CreateMaybeMessage<::caffe::FillerParameter>(GetArenaNoVirtual());
                                                          ^
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h: In member function 'caffe::BlobShape* caffe::ParameterParameter::mutable_shape()':
/home/opt/caffe/.build_release/include/caffe/proto/caffe.pb.h:23884:15: error: 'CreateMaybeMessage' was not declared in this scope
     auto* p = CreateMaybeMessage<::caffe::BlobShape>(GetArenaNoVirtual());

**Comment by junwenchen** [comment]
@l2009312042 

hi, did you solve it? I am also facing this problem.

**Comment by l2009312042** [comment]
@junwenchen   not yet

**Comment by l2009312042** [comment]
i have solve it. 
input  "whereis protoc "
 display  two version  protobuf   
i remove  one of it  by apt-get purge --auto-remove protobuf-compiler 
then  rebuild caffe  and  caffe2  by 
mkdir build    cd build  cmake ..   make -j4   make install  

it's ok   now
