### ISSUE TITLE
cmake errors

### ISSUE THREAD

**Issue by yunzhe-tao** [facebookresearch/video-nonlocal-net#7]
Hi, I was trying to follow the installation example of Xiaolong. However, I got the error messages as follows when doing "cmake -DCMAKE_INSTALL_PREFIX:PATH=/path/to/caffe2/build/install .." :

cmake: /my/path/to/anaconda2/envs/caffe2/bin/../lib/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (requested by cmake)
cmake: /my/path/to/anaconda2/envs/caffe2/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.9' not found (requested by cmake)
cmake: /my/path/to/anaconda2/envs/caffe2/bin/../lib/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (requested by cmake)

I am wondering why this happens. Thank you.

**Comment by xiaolonw** [comment]
maybe your gcc version is too old? 
can you do "conda install gcc" ?

**Comment by yunzhe-tao** [comment]
I did both "conda install gcc" and "conda update gcc". After that, I saw my gcc version is 4.8.5. Is it not still not new enough for cmake?

**Comment by xiaolonw** [comment]
i think 4.8.5 is good enough 
have you also change your LD_LIBRARY_PATH  ?

**Comment by yunzhe-tao** [comment]
Yes. I did the same as you suggested. But I found that there is no GLIBCXX_3.4.20 in any of the lib added to LD_LIBRARY_PATH. Then I saw anaconda2/lib64 has that version and also added it to LD_LIBRARY_PATH, but still didn't work.

**Comment by yunzhe-tao** [comment]
Alright, thank you! I will figure it out by myself. You can close the issue if you want.

**Comment by amznero** [comment]
Maybe the libstdc++.so.6 -> system's(old) /usr/.so.
I fix this by
`mv libstdc++.so.6 libstdc++.so.6.old` 
`ln -s libstdc++.so.6.0.24 libstdc++.so.6`
